version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    AWS_REGION: eu-west-3
    REPOSITORY_URI: 863518447118.dkr.ecr.eu-west-3.amazonaws.com/discovery-server

phases:
  pre_build:
    commands:
      - echo "Connexion à ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "Construction de l'image Docker..."
      - docker build -t discovery-server .
      - docker tag discovery-server:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Push de l'image vers ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Image poussée avec succès !"

artifacts:
  files:
    - '**/*'
