spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: default

# Logging configuration
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
    # Log Eureka-specific info (Optional)
    org:
      springframework:
        cloud:
          netfliex:
            eureka:
              client:
                level: INFO

# Management and Metrics Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: PetClinicMetrics
        step: 30s
  endpoint:
    health:
      show-details: always
